### ISSUE TITLE
Add keynote showcase section on homepage

### ISSUE THREAD

**Issue by frdeso** [pyconca/2017-web#24]
Keynote description, head shot and twitter handle.

**Comment by onebit0fme** [comment]
Lynn Root added in https://github.com/pyconca/2017-web/pull/38

**Comment by onebit0fme** [comment]
Camille Fournier added in https://github.com/pyconca/2017-web/pull/40

**Comment by onebit0fme** [comment]
Julia Evans added in #42

**Comment by onebit0fme** [comment]
Mariatta Wijaya  in #46
