### ISSUE TITLE
Bug report received on organizer@pycon.ca

### ISSUE THREAD

**Issue by frdeso** [pyconca/2017-web#27]
Hi folks!

I was checkout out the Pycon2017 conference website and noticed what's probably a bug.

If you go to a non-existent page (like [1]) you get a 404 page that includes a bunch of internal configuration information, which is probably not something you want. The 404 page itself says:

"You're seeing this error because you have DEBUG = True in your Django settings file."

[1] https://2017.pycon.ca/a

Cheers,

**Comment by myles** [comment]
🛠  and 🚀
