### ISSUE TITLE
Hotel info

### ISSUE THREAD

**Issue by annaelleduff** [pyconca/2017-web#55]
Hotel Travelodge Montréal Centre ***
50, boulevard René-Lévesque West – Montréal (Québec) H2Z 1A2
 
ENGLISH
Located in the heart of downtown, the Travelodge Montréal Centre is a choice destination in order to fully enjoy our beautiful city. In addition to the numerous attractions nearby, the hotel is two blocks away from the metro stations Place d’Armes (orange line) and Saint-Laurent (green line). The Travelodge Montréal Centre offers a buffet-style continental breakfast, complimentary Wi-Fi and free access to our new gym.
 
 
By email:
reserve@travelodgemontreal.ca cid:image008.png@01D33945.C62C1220 (Please mention Block name: Pycon Canada  & Block ID: 482 452 )
 
By phone:
514-874-9090, option 1 (Please mention Block name:  Pycon Canada  & Block ID: 482 451 )
Toll free: 1-800-363-6535, option 1
Pycon Canada – Block ouvert 2017

FRANÇAIS

Situé en plein cœur du centre-ville, l’Hôtel Travelodge Montréal Centre est une destination de choix pour profiter pleinement de notre belle ville. En plus des nombreuses attractions à proximité, l’hôtel est à deux pas des stations de métro Place d’Armes (ligne orange) et Saint-Laurent (ligne verte). L’Hôtel Travelodge Montréal Centre offre un petit-déjeuner continental style buffet, le Wi-Fi gratuit et l’accès gratuit à notre nouvelle salle de gym!
 
Par courriel:
reserve@travelodgemontreal.ca cid:image008.png@01D33945.C62C1220 (Merci de mentionner le nom du bloc : Pycon Canada  & Block ID: 482 452)
 
Par téléphone:
514-874-9090, option 1 (Merci de mentionner le nom du bloc : Pycon Canada  & Block ID: 482 452)
Sans frais : 1-800-363-6535, option 1

![hotel travelodge haute qualite](https://user-images.githubusercontent.com/1771517/31048190-5bb932ac-a5e6-11e7-83f2-a335953dc975.jpg)

**Comment by myles** [comment]
Just need to deploy.
