### ISSUE TITLE
Schedule translation

### ISSUE THREAD

**Issue by frdeso** [pyconca/2017-web#59]
The word schedule translates to "Horaire"

**Comment by frdeso** [comment]
Breakfast = "Déjeuner"
Lunch = "Dîner"
Break = "Pause café"

**Comment by frdeso** [comment]
Morning Keynote = "Présentation invitée de début de journée"
Afternoon Keynote= "Présentation invitée de fin de journée"
Registration & Breakfast="Inscription et déjeuner"
Welcome & Morning Keynote = "Accueil & présentation invitée de début de journée"
Closing keynote=" Présentation invitée de fermeture"

**Comment by myles** [comment]
Done.
