### ISSUE TITLE
Bell logo distorted on IE

### ISSUE THREAD

**Issue by annaelleduff** [pyconca/2017-web#68]
> In your website’s sponsors page. The Bell logo is distorted when I launch the page in Internet Explorer. The logo is fine on Chrome and Firefox. Can you please take a look and modify accordingly.

**Comment by frdeso** [comment]
![image](https://user-images.githubusercontent.com/1723756/31626644-83d83000-b278-11e7-9daa-f413ecd96db1.png)

**Comment by frdeso** [comment]
A friend sent me this:
![ryu7ahl](https://user-images.githubusercontent.com/1723756/31626657-9451cd1a-b278-11e7-84eb-0e54d93a8aa8.png)

**Comment by frdeso** [comment]
I used this webapp and was able to see the issue : https://netrenderer.com/index.php

**Comment by myles** [comment]
Fixed the IE 9 SVG render issue.
