### ISSUE TITLE
Display top menu on mobile version

### ISSUE THREAD

**Issue by frdeso** [pyconca/2017-web#71]
At least the schedule link should be visible in the mobile homepage.

**Comment by myles** [comment]
This was fixed a while ago but they forgot to remove a `display: none`.

I've deployed the fix and removed the _Buy Ticket_ button for a _Schedule_ button as most people when visiting the website will care most about that.

**Comment by frdeso** [comment]
Great idea to change add a large schedule button!

Le 7 nov. 2017 09:14, "Myles Braithwaite" <notifications@github.com> a
écrit :

This was fixed a while ago but they forgot to remove a display: none.

I've deployed the fix and removed the *Buy Ticket* button for a *Schedule*
button as most people when visiting the website will care most about that.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/pyconca/2017-web/issues/71#issuecomment-342494601>, or mute
the thread
