### ISSUE TITLE
Fix schedule view on mobile

### ISSUE THREAD

**Issue by myles** [pyconca/2017-web#72]

**Comment by frdeso** [comment]
Is it deployed?

**Comment by myles** [comment]
No, I had to run after I pushed it. Will try later today but am really busy right now.

**Comment by frdeso** [comment]
Okay no problem

2017-10-25 11:19 GMT-04:00 Myles Braithwaite <notifications@github.com>:

**Comment by frdeso** [comment]
It looks great! Thank you Myles
!
