### ISSUE TITLE
Add sprints location on the schedule

### ISSUE THREAD

**Issue by frdeso** [pyconca/2017-web#75]
They will be held at the UQAM Chaufferie du Pavillon Coeur des sciences, room CO-R700 (175 Avenue du Président-Kennedy)
Les sprints se tiendront à la Chaufferie du Pavillon Coeur des sciences de l'UQAM, salle CO-R700 (175 Avenue du Président-Kennedy)

https://2017.pycon.ca/schedule/sprints/

**Comment by myles** [comment]
I've deployed the English translation. Waiting on the page to be translated into French.

**Comment by myles** [comment]
Got French translation.
