### ISSUE TITLE
Language toggle is hidden on mobile screen

### ISSUE THREAD

**Issue by onebit0fme** [pyconca/2017-web#9]
On a small screen, top navigation is hidden along with the language toggle.

Styles are located in https://github.com/pyconca/2017-patterns repo.

**Comment by frdeso** [comment]
It seems that the navigation bar is hidden too in mobile.

**Comment by ryanwilsonperkin** [comment]
@frdeso related style rule: https://github.com/pyconca/2017-patterns/blob/master/src/assets/toolkit/styles/components/_head.scss#L37
